name: Dependabot auto-merge

on:
  pull_request:
    branches: [main]

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      pull-requests: write # to be able to comment on released pull requests

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
